# Generated by Django 5.0.6 on 2024-07-09 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_rename_user_customuser"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="last_login",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="last login"
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="password",
            field=models.CharField(
                default="hola", max_length=128, verbose_name="password"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="customuser",
            name="username",
            field=models.CharField(
                default="hola",
                error_messages={"unique": "A user with that username already exists."},
                help_text="Required. 50 characters or fewer. Lowercase letters and digits only.",
                max_length=50,
                unique=True,
                verbose_name="username",
            ),
            preserve_default=False,
        ),
    ]
